version: '3.2'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/${SPRING_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - FILEPATH=${FILEPATH}
      - URL=${URL}
      - KEYNAME=${KEYNAME}
      - APIKEY=${APIKEY}
    networks:
      - backend-network

  postgresdb:
    image: postgres:13.1-alpine
    container_name: postgresdb
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${SPRING_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  db-data:
